package com.wings.picexchange.ui.theme

import androidx.compose.ui.graphics.Color

// Cohesive teal-forward palette, calm and age-neutral, tuned for WCAG-AA contrast.
// Light scheme
val LightPrimary = Color(0xFF006B5A)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF7BF8DD)
val LightOnPrimaryContainer = Color(0xFF00201A)
val LightSecondary = Color(0xFF4A635B)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCDE9DD)
val LightOnSecondaryContainer = Color(0xFF06201A)
val LightTertiary = Color(0xFF436277)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFC8E6FF)
val LightOnTertiaryContainer = Color(0xFF001E2E)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF4FBF7)
val LightOnBackground = Color(0xFF171D1B)
val LightSurface = Color(0xFFF4FBF7)
val LightOnSurface = Color(0xFF171D1B)
val LightSurfaceVariant = Color(0xFFDBE5DF)
val LightOnSurfaceVariant = Color(0xFF3F4945)
val LightOutline = Color(0xFF6F7975)

// Dark scheme
val DarkPrimary = Color(0xFF5BDBC1)
val DarkOnPrimary = Color(0xFF00382E)
val DarkPrimaryContainer = Color(0xFF005143)
val DarkOnPrimaryContainer = Color(0xFF7BF8DD)
val DarkSecondary = Color(0xFFB1CCC1)
val DarkOnSecondary = Color(0xFF1C352D)
val DarkSecondaryContainer = Color(0xFF324B43)
val DarkOnSecondaryContainer = Color(0xFFCDE9DD)
val DarkTertiary = Color(0xFFAACBE3)
val DarkOnTertiary = Color(0xFF103447)
val DarkTertiaryContainer = Color(0xFF2A4A5E)
val DarkOnTertiaryContainer = Color(0xFFC8E6FF)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF0E1513)
val DarkOnBackground = Color(0xFFDEE4E0)
val DarkSurface = Color(0xFF0E1513)
val DarkOnSurface = Color(0xFFDEE4E0)
val DarkSurfaceVariant = Color(0xFF3F4945)
val DarkOnSurfaceVariant = Color(0xFFBFC9C3)
val DarkOutline = Color(0xFF89938E)
